<<<<<<< HEAD
language: node_js
node_js:
- node
cache: npm
install:
- npm install
script:
- npm run build
deploy: 
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_19c402d84138_key -iv $encrypted_19c402d84138_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@121.199.50.51 pwd
=======
language: node_js
node_js: "node"

cache: npm
install: npm install
script: npm run build

# after_success:
#   - cd ./dist
#   - git init
#   - git config --global user.name "${U_NAME}"
#   - git config --global user.email "${U_EMAIL}"
#   - git add .
#   - git commit -m "Automatically update from travis-ci"
#   - git push origin master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
>>>>>>> 943eeb307defce393321c03c44ea16a6c5290547
