language: node_js
node_js:
- node
cache: npm
install:
- npm install
script:
- npm run build
deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_19c402d84138_key -iv $encrypted_19c402d84138_iv
  -in deploy_key.enc -out ./deploy_key -d

