language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
before_install:
  - openssl aes-256-cbc -K $encrypted_19c402d84138_key -iv $encrypted_19c402d84138_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
  - ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add dist
  - git commit -m "add dist"
  - git push --force --quiet "https://${GITHUB_TOKEN2}@${GH_REF}" master:master
  - ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd 'cd /home/vue/xblog-vue  && git pull origin pages'
# after_success:

env:
  global:
    - GH_REF=github.com:AVAL-NIX/xblog-vue.git