language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run build
deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: dist
true:
  branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_19c402d84138_key -iv $encrypted_19c402d84138_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
- ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd 'cd /home/vue/xblog-vue'
after_script:
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "add dist"
  - git push origin master
after_success:
- ssh -i ./deploy_key root@$SERVER_IP_ADDRESS pwd 'cd /home/vue/xblog-vue  && git pull origin master'